// Generated by CoffeeScript 1.7.1
(function() {
  var baseDirectory, bs, c, e, key, path, re, sh, value;

  path = require('path');

  sh = require("shelljs");

  c = require('multi-config');

  process.on('uncaughtException', function(err) {
    return console.error(err.stack);
  });

  global.p = console.log;

  baseDirectory = sh.pwd();

  re = /\.*\/bin$/;

  global.baseDirectory = baseDirectory.split(re)[0];

  require("./require");

  module.exports = {
    runner: require("./runner"),
    tasks: require("./tasks")
  };

  try {
    bs = testRequire("bootstrap");
    for (key in bs) {
      value = bs[key];
      module.exports[key] = value;
    }
  } catch (_error) {
    e = _error;
  }

}).call(this);
