// Generated by CoffeeScript 1.7.1
(function() {
  var dir, path, requirePath, _i, _len, _ref, _require;

  path = require('path');

  requirePath = function(projectDir, _path) {
    return path.join(baseDirectory, projectDir, _path);
  };

  _require = function(projectDir, _path) {
    return require(requirePath(projectDir, _path));
  };

  global.fixtureRequire = function(_path) {
    return _require("test/fixtures", _path);
  };

  global.fixturePath = function(_path) {
    return requirePath("test/fixtures", _path);
  };

  _ref = ["js", "lib", "src", "test"];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    dir = _ref[_i];
    global["" + dir + "Require"] = (function(dir) {
      return function(_path) {
        return _require(dir, _path);
      };
    })(dir);
  }

}).call(this);
