// Generated by CoffeeScript 1.7.1
(function() {
  var exec, jasmineRunner, nodeunit, nodeunitRunner, print, spawn, systemRunner, _ref;

  nodeunit = require('nodeunit');

  _ref = require('child_process'), spawn = _ref.spawn, exec = _ref.exec;

  print = require('sys').print;

  systemRunner = function(commandString) {
    var command;
    command = exec(commandString);
    command.stdout.on('data', function(data) {
      return print(data.toString());
    });
    return command.stderr.on('data', function(data) {
      return print(data.toString());
    });
  };

  nodeunitRunner = function(_path) {
    var command;
    command = "nodeunit " + _path;
    return systemRunner(command);
  };

  jasmineRunner = function(_path) {
    var command;
    command = "jasmine-node --coffee --verbose " + _path;
    return systemRunner(command);
  };

  module.exports = {
    system: systemRunner,
    jasmine: jasmineRunner,
    nodeunit: nodeunitRunner
  };

}).call(this);
